import { TransportLeg } from "@/lib/demoData";

export const DEMO_VIETNAM_LA_ROUTE: TransportLeg[] = [
  {
    id: "demo-vn-la-1",
    legNumber: 1,
    type: "domestic",
    mode: "truck_heavy",
    origin: {
      name: "Nhà máy dệt may Bình Dương",
      lat: 10.9804,
      lng: 106.6519,
      type: "address",
    },
    destination: {
      name: "Cảng Cát Lái, TP.HCM",
      lat: 10.7531,
      lng: 106.7567,
      type: "port",
    },
    distanceKm: 35,
    emissionFactor: 0.105,
    co2Kg: 3.68,
    routeType: "road",
  },
  {
    id: "demo-vn-la-2",
    legNumber: 2,
    type: "international",
    mode: "ship",
    origin: {
      name: "Cảng Cát Lái, TP.HCM",
      lat: 10.7531,
      lng: 106.7567,
      type: "port",
    },
    destination: {
      name: "Cảng Long Beach, Los Angeles",
      lat: 33.7701,
      lng: -118.1937,
      type: "port",
    },
    distanceKm: 14500,
    emissionFactor: 0.016,
    co2Kg: 232.0,
    routeType: "sea",
  },
  {
    id: "demo-vn-la-3",
    legNumber: 3,
    type: "domestic",
    mode: "truck_light",
    origin: {
      name: "Cảng Long Beach, Los Angeles",
      lat: 33.7701,
      lng: -118.1937,
      type: "port",
    },
    destination: {
      name: "Kho hàng Downtown LA",
      lat: 34.0522,
      lng: -118.2437,
      type: "address",
    },
    distanceKm: 45,
    emissionFactor: 0.089,
    co2Kg: 4.01,
    routeType: "road",
  },
];

export const DEMO_SHIPMENTS = [
  {
    id: "SHIP-2024-001",
    productId: "demo-product-001",
    productName: "Áo T-shirt Organic Cotton",
    sku: "DEMO-SKU-001",
    status: "in_transit" as const,
    progress: 65,
    origin: "Bình Dương, Vietnam",
    destination: "Los Angeles, California, USA",
    estimatedArrival: "2024-02-15",
    departureDate: "2024-01-20",
    currentLocation: "Thái Bình Dương - Gần Hawaii",
    legs: DEMO_VIETNAM_LA_ROUTE,
    totalCO2: 239.69,
    carrier: "COSCO Shipping",
    containerNo: "CSLU1234567",
    isDemo: true,
  },
  {
    id: "SHIP-2024-002",
    productId: "demo-product-003",
    productName: "Váy Linen Blend",
    sku: "DEMO-SKU-003",
    status: "delivered" as const,
    progress: 100,
    origin: "Đà Nẵng, Vietnam",
    destination: "Tokyo, Japan",
    estimatedArrival: "2024-01-22",
    departureDate: "2024-01-18",
    currentLocation: "Đã giao - Narita Airport",
    legs: [
      {
        id: "leg-jp-1",
        legNumber: 1,
        type: "domestic" as const,
        mode: "truck_heavy" as const,
        origin: {
          name: "Nhà máy Đà Nẵng",
          lat: 16.0544,
          lng: 108.2022,
          type: "address" as const,
        },
        destination: {
          name: "Sân bay Đà Nẵng",
          lat: 16.0439,
          lng: 108.1997,
          type: "airport" as const,
        },
        distanceKm: 5,
        emissionFactor: 0.105,
        co2Kg: 0.53,
        routeType: "road" as const,
      },
      {
        id: "leg-jp-2",
        legNumber: 2,
        type: "international" as const,
        mode: "air" as const,
        origin: {
          name: "Sân bay Đà Nẵng",
          lat: 16.0439,
          lng: 108.1997,
          type: "airport" as const,
        },
        destination: {
          name: "Sân bay Narita, Tokyo",
          lat: 35.7647,
          lng: 140.3864,
          type: "airport" as const,
        },
        distanceKm: 3850,
        emissionFactor: 0.602,
        co2Kg: 2317.7,
        routeType: "air" as const,
      },
    ],
    totalCO2: 2318.23,
    carrier: "Vietnam Airlines Cargo",
    containerNo: "VN-AIR-789456",
    isDemo: true,
  },
  {
    id: "SHIP-2024-003",
    productId: "demo-product-002",
    productName: "Quần Jeans Recycled Denim",
    sku: "DEMO-SKU-002",
    status: "pending" as const,
    progress: 0,
    origin: "Bình Dương, Vietnam",
    destination: "Rotterdam, Netherlands",
    estimatedArrival: "2024-03-05",
    departureDate: "2024-02-01",
    currentLocation: "Đang chờ xếp hàng - Cảng Cát Lái",
    legs: [
      {
        id: "leg-eu-1",
        legNumber: 1,
        type: "domestic" as const,
        mode: "truck_light" as const,
        origin: {
          name: "Nhà máy Q.12, TP.HCM",
          lat: 10.8675,
          lng: 106.6417,
          type: "address" as const,
        },
        destination: {
          name: "Cảng Cát Lái, TP.HCM",
          lat: 10.7531,
          lng: 106.7567,
          type: "port" as const,
        },
        distanceKm: 28,
        emissionFactor: 0.089,
        co2Kg: 2.49,
        routeType: "road" as const,
      },
      {
        id: "leg-eu-2",
        legNumber: 2,
        type: "international" as const,
        mode: "ship" as const,
        origin: {
          name: "Cảng Cát Lái, TP.HCM",
          lat: 10.7531,
          lng: 106.7567,
          type: "port" as const,
        },
        destination: {
          name: "Cảng Rotterdam, Hà Lan",
          lat: 51.9244,
          lng: 4.4777,
          type: "port" as const,
        },
        distanceKm: 17200,
        emissionFactor: 0.016,
        co2Kg: 275.2,
        routeType: "sea" as const,
      },
    ],
    totalCO2: 277.69,
    carrier: "Maersk Line",
    containerNo: "MAEU9876543",
    isDemo: true,
  },
];
